baseurl = "https://sowmyamanojna.github.io/hugo-minimal-project/"
languageCode = "en-us"
title = "Loan Default Prediction"
theme = "minimal-project"
enableEmoji = true
toc = true

# Configure the Markdown renderer.
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content.
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

# Taxonomies.
[taxonomies]
  author = "authors"

#
# Personalization params
#
[params]
    # project specific params
    course_code_session = "MS4610 Project, Fall 2020"
    course_name =  "Intoduction to Data Analytics"
    university = "Indian Institute of Technology Madras"

    math = true
    # Specify which directory to take main content from
    mainSections = ["main"]

    # social share links to appear at the end
    socialShare = true
    # Sets specific share to appear on posts (default behavior is to appear)
    socialShareTwitter = true
    socialShareGoogleplus = true
    socialShareFacebook = true
    socialShareReddit = true
    socialShareLinkedin = true
    socialShareStumbleupon = true
    socialSharePinterest = true
    socialShareEmail = true

    # theme's color scheme
    first_color ="#f8f8f8"
    first_border_color ="#e7e7e7"
    first_text_color ="#333"

    # second_color ="white"
    second_color ="white"
    second_text_color ="#333"

    header_color ="#f8f8f8"
    header_text_color ="rgb(51, 51, 51)"

    header_link_color ="#777"
    header_link_hover_color ="rgb(51, 51, 51)"

    # All intro links - pdf, reports, code
    proposal = true
    proposal_image = "img/proposal.png"
    proposal_file = "docs/proposal.pdf"
    midterm = true
    midterm_image = "img/ff_paper_mid_term.png"
    midterm_file = "docs/mid_term.pdf"
    final = false
    final_image = "img/final.png"
    final_file = "docs/final.pdf"
    code = "https://github.com/sowmyamanojna/Loan-Default-Prediction"
    wandb = ""

#
# Sets Social Media icons to appear and link to your account. Value should be your
# username unless otherwise noted. Icons appear at the top of the page.
#
[social]
    # Coding Communities
    github = "sowmyamanojna/Loan-Default-Prediction"
    gitlab = ""
    stackoverflow = "" # User Number
    bitbucket = ""
    jsfiddle = ""
    codepen = ""
    # Visual Art Communities
    deviantart = ""
    flickr = ""
    behance = ""
    dribbble = ""
    # Publishing Communities
    wordpress = ""
    medium = ""
    # Professional/Business Oriented Communities
    linkedin = ""
    linkedin_company = ""
    foursquare = ""
    xing = ""
    slideshare = ""
    # Social Networks
    facebook = ""
    googleplus = ""
    reddit = ""
    quora = ""
    youtube = ""
    vimeo = ""
    whatsapp = "" # WhatsApp Number
    # WeChat and QQ need testing.
    wechat = ""
    qq = "" # User ID Number
    instagram = ""
    tumblr = ""
    twitter = ""
    skype = ""
    snapchat = ""
    pinterest = ""
    telegram = ""
    vine = ""
    googlescholar = ""
    orcid = ""
    researchgate = ""
    # Email
    email = ""

#
# Adjust privacy settings
# See: https://gohugo.io/about/hugo-and-gdpr/
#
[privacy]
    [privacy.disqus]
      disable = true

    [privacy.googleAnalytics]
      disable = true
      anonymizeIP = true
      respectDoNotTrack = true
      useSessionStorage = true

    [privacy.instagram]
      disable = false
      simple = true

    [privacy.twitter]
      disable = false
      enableDNT = true
      simple = true

    [privacy.vimeo]
      disable = true
      simple = true

    [privacy.youtube]
      disable = false
      privacyEnhanced = true

#
# In simple mode for Instagram and a site styled with Bootstrap 4, 
# you may want to disable the inlines styles provided by Hugo:
# See: https://gohugo.io/about/hugo-and-gdpr/
#
[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

